### ISSUE TITLE
Impossible To Load World On 1.19.4 [Bug] 

### ISSUE THREAD

**Issue by Panedwards** [quiqueck/BCLib#87]
### What happened?

java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/structure]: [bclib:test_structure]

(This crashes the game the second you try to make a new world)

### BCLib

2.3.0

### Fabric API

0.14.19

### Fabric Loader

1.19.4

### Minecraft

1.19.3

### Relevant log output

```shell
Client Log: https://mclo.gs/UCsV1WB

Crash Log: https://mclo.gs/9phyrvA
```

### Other Mods

```shell
(in the log)
```

**Comment by lospejos** [comment]
Also faced this bug on `fabric-api 0.79.0+1.19.4`.

Mods installed (alphabetically):
```
bclib-2.3.0.jar
better-nether-8.2.0.jar
fabric-api-0.79.0+1.19.4.jar
ferritecore-5.2.0-fabric.jar
iris-mc1.19.4-1.6.1.jar
lithium-fabric-mc1.19.4-0.11.1.jar
memoryleakfix-fabric-1.17+-1.0.0.jar
modmenu-6.2.1.jar
reeses_sodium_options-1.5.0+mc1.19.4-build.72.jar
sodium-extra-0.4.18+mc1.19.4-build.100.jar
sodium-fabric-mc1.19.4-0.4.10+build.24.jar
starlight-1.1.1+fabric.ae22326.jar
```

**Comment by CamperSamu** [comment]
[Works on latest BCLib (2.3.1)](https://modrinth.com/mod/bclib/version/2.3.1), please close the issue.
![image](https://user-images.githubusercontent.com/32773961/236064475-3d1112db-0bf7-4038-80e1-367eb2fc075a.png)

> ### Mods
> ```apache
>   [✔] alternate-current-mc1.19-1.5.0
>   [✔] anti-xray-1.3.0-Fabric-1.19.4
>   [✔] armor-stand-editor-2.1.0+1.19.4-rc2
>   [✔] bclib-2.3.1
>   [✔] c2me-base-mc1.19.4-0.2.0+alpha.10.51
>   [✔] c2me-fabric-mc1.19.4-0.2.0+alpha.10.51
>   [✔] c2me-fixes-worldgen-vanilla-bugs-mc1.19.4-0.2.0+alpha.10.51
>   [✔] c2me-notickvd-mc1.19.4-0.2.0+alpha.10.51
>   [✔] c2me-opts-chunkio-mc1.19.4-0.2.0+alpha.10.51
>   [✔] c2me-opts-math-mc1.19.4-0.2.0+alpha.10.51
>   [✔] c2me-opts-scheduling-mc1.19.4-0.2.0+alpha.10.51
>   [✔] c2me-opts-worldgen-general-mc1.19.4-0.2.0+alpha.10.51
>   [✔] c2me-opts-worldgen-vanilla-mc1.19.4-0.2.0+alpha.10.51
>   [✔] c2me-rewrites-chunkio-mc1.19.4-0.2.0+alpha.10.51
>   [✔] c2me-server-utils-mc1.19.4-0.2.0+alpha.10.51
>   [✔] c2me-threading-chunkio-mc1.19.4-0.2.0+alpha.10.51
>   [✔] c2me-threading-lighting-mc1.19.4-0.2.0+alpha.10.51
>   [✔] cloth-config-10.0.96-fabric
>   [✔] Clumps-fabric-1.19.4-10.0.0.2
>   [✔] Debugify-1.19.4+2.2
>   [✔] entity-view-distance-1.1.1+1.19.4
>   [✔] fabric-api-0.80.0+1.19.4
>   [✔] fabric-carpet-1.19.4-1.4.101+v230319
>   [✔] fabric-language-kotlin-1.9.4+kotlin.1.8.21
>   [✔] fabrictailor-2.1.1
>   [✔] ferritecore-5.2.0-fabric
>   [✔] global_packs-fabric-1.19.4-1.16_fabric
>   [✔] holograms-1.5.1+1.19.4-legacy-edition
>   [✔] image2map-0.4.1
>   [✔] Incendium_1.19.4_v5.2.1
>   [✔] InventorySorter-1.8.10-1.19.4
>   [✔] jline4mcdsrv-0.4.2
>   [✔] jsst-1.19.4-0.3.4
>   [✔] krypton-0.2.2
>   [✔] leukocyte-0.3.5+1.19.4-rc2
>   [✔] lithium-fabric-mc1.19.4-0.11.1
>   [✔] LuckPerms-Fabric-5.4.66
>   [✔] mcmtfabric-1.4.0
>   [✔] memoryleakfix-fabric-1.17+-1.0.0
>   [✔] mixintrace-1.1.1+1.17
>   [✔] mods-command-mc1.19.4-1.1.2
>   [✔] NoChatReports-FABRIC-1.19.4-v2.1.1
>   [✔] Nullscape_1.19.4_v1.2.1
>   [✔] polyconfig-0.3.6
>   [✔] polydex-0.2.1+1.19.4-rc2
>   [✔] PolyMc-5.3.2+1.19.3
>   [✔] polymer-bundled-0.4.7+1.19.4
>   [✔] raknetify-fabric-0.1.0+alpha.5.72-all
>   [✔] semblance-1.1.4
>   [✔] servercore-fabric-1.3.5+1.19.4
>   [✔] servertick-mc1.19-1.7
>   [✔] slumber-1.1.0
>   [✔] SmartBrainLib-fabric-1.19.4-1.9
>   [✔] smoothboot-fabric-1.19.4-1.7.0
>   [✔] spark-1.10.37-fabric
>   [✔] StackDeobfuscator-1.3.1+fabric.d71a3c3
>   [✔] starlight-1.1.1+fabric.ae22326
>   [✔] styled-chat-2.1.6+1.19.4
>   [✔] styled-nicknames-1.2.0+1.19.3
>   [✔] styled-sidebars-1.0.1+1.19.4
>   [✔] styledplayerlist-2.3.0+1.19.3
>   [✔] tectonic-mod-mc1.19.3-v1.1.10
>   [✔] TerraBlender-fabric-1.19.4-2.2.0.156
>   [✔] Terralith_1.19.4_v2.3.7b
>   [✔] ViaBackwards-4.6.1
>   [✔] viafabric-0.4.10+33-dev
>   [✔] ViaRewind-2.0.3
>   [✔] vmp-fabric-mc1.19.4-0.2.0+beta.7.72-all
> ```
